# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
